### ISSUE TITLE
Cannot deploy to now-serve

### ISSUE THREAD

**Issue by mrmartineau** [zeit/now-serve#18]
I mentioned this on the Zeit Slack channel yesterday but was not able to resolve it so I thought it best to log the issue here.

I am seeing this error when I run `ns`, `ns -n foobarz`

```sh
 ❯ $ ns -n foobarz
/usr/local/lib/node_modules/now-serve/dist/bin/ns:108
  throw err;
  ^

Error: Could not get a unique tmp filename, max tries reached
    at _getTmpNameSync (/usr/local/lib/node_modules/now-serve/node_modules/tmp/lib/tmp.js:198:9)
    at Object._createTmpDirSync [as dirSync] (/usr/local/lib/node_modules/now-serve/node_modules/tmp/lib/tmp.js:328:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/now-serve/dist/bin/ns:98:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

I tried using sudo and got more output:

```sh
 ❯ $ sudo ns -a 'debug'
Password:
> [debug] Checking for updates.
> [debug] Up to date (0.25.1).
> Deploying /private/tmp/now-serve-4a2636fdfe4cae9fc797dc4eb11d1b48
[debug] `package.json` found, assuming `deploymentType` = `npm`
> [debug] locating files /private/tmp/now-serve-4a2636fdfe4cae9fc797dc4eb11d1b48: 39.529ms
> [debug] Getting files: 45.418ms
> [debug] Computing hashes: 2033.284ms
> [debug] /now/create: 1561.948ms
> Using Node.js 6.6.0 (default)
> Ready! https://ns-qutpzofznr.now.sh (copied to clipboard) [4s]
> [debug] Will upload 28 files in 3 steps of 10 uploads.
> [debug] /sync #1 /private/tmp/now-serve-4a2636fdfe4cae9fc797dc4eb11d1b48/content/assets/dist/videos/tmw/showreel.mp4: 160.813ms
> [debug] bailing on creating due to 413
> Error! Upload failed
> Error! Unexpected error. Please try later. (Response error)
```

What is strange is that there is no package.json file in the directory but it thinks that there is. Any ideas why I might need sudo? the showreel file is a large video but as a paid subscriber I did not know that there were any filesize limits.

**Comment by OlliV** [comment]
You shouldn't need sudo. I think the `package.json` it find belongs to `micro-list`.

**Comment by leo** [comment]
Exactly. `ns` is wrapping your stuff into a folder called "content", which has a package.json file next to it. This file specifies that the folder needs to be served over HTTP ([micro-list](https://github.com/zeit/micro-list)).

**Comment by mrmartineau** [comment]
After a bit of discussion on the Slack chat with @OlliV, it seems that I was hitting the file-size limit that zeit has in place. Deployments work after I remove the offending files.. Some nicer error messaging would be useful though.

**Comment by leo** [comment]
@mrmartineau Ahh, got it! So if it's related to [now](https://github.com/zeit/now) itself, please report it there.

**Comment by mrmartineau** [comment]
@leo I didn't know that it was until I had @OlliV's help..

**Comment by leo** [comment]
@mrmartineau Yep, I did understand that 😊

**Comment by mrmartineau** [comment]
cool 👍
