### ISSUE TITLE
Option to enable Password Protection for static sites

### ISSUE THREAD

**Issue by vinaypuppal** [zeit/now-serve#21]
Hi, I deployed a static site with `now-serve`, is there any option to make the static site `Password Protected`.

If not I found http://npm.im/http-auth package which I can use to setup `Password Protection` by running simple node server.

So can this `feature` be built in to `now-serve`and provide some config option to enable it.
And it would be nice to have this feature in [list](https://github.com/zeit/list) package as well.

**Comment by leo** [comment]
IF we're going to implement this, it should be part of [list](https://github.com/zeit/list). 😊
