### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by olimart** [zeit/now-serve#5]
Any idea what's going on when running `ns index.html` ?

```
/usr/local/lib/node_modules/now-serve/dist/bin/ns:124
  var fileName = _path2.default.parse(current).base,
                                ^
TypeError: Object #<Object> has no method 'parse'
    at Object.<anonymous> (/usr/local/lib/node_modules/now-serve/dist/bin/ns:124:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by leo** [comment]
Just tried to replicate that behaviour, but it seems to work completely fine for me. Which version of node are you running it on?

**Comment by olimart** [comment]
Used to run `1.4.9`. Upgraded to `3.8.9` but same result.

**Comment by leo** [comment]
@olimart Are you talking about npm? Because `nvm` says that there's no version `3.8.9` of node.

**Comment by olimart** [comment]
never mind I upgraded node and working fine now. Thanks for your help.

**Comment by olimart** [comment]
Actually, is package.json required for single file upload (I don't have any at the moment)?

```
now index.html
> Deploying "/Sites/index.html"
> Error! Failed to read JSON in "/Sites/index.html/package.json"
```

**Comment by leo** [comment]
@olimart No, it should create one in the temporary directory by default... Hmmm...
